


test_scarf_iris = function() {
  message("Training scarf on iris")


  # 1. Definir la receta
  # Usamos Species como Target. Las numéricas serán procesadas por SCARF.
  rec_spec_iris <- recipes::recipe(Species ~ ., data = iris) |>
    step_extract_latent(recipes::all_numeric_predictors(), epochs = 2) |>

  # 2. Entrenar la receta (Ejecuta el PREP y entrena SCARF)
  message("Entrenando SCARF con iris...")
  rec_trained_iris <- recipes::prep(rec_spec_iris, training = iris)

  # 3. Aplicar la receta (Ejecuta el BAKE)
  message("Aplicando transformación latente...")
  iris_transformed <- recipes::bake(rec_trained_iris, new_data = iris)

  # 4. Verificaciones de éxito:
  print(dim(iris_transformed))
  # Debería mostrar: [150 filas, 257 columnas]
  # (1 de la variable Species + 256 de las dimensiones latentes)

  dplyr::glimpse(iris_transformed[, 1:5])


}




test_scarf_unswnb15 = function() {

  # 1. Definir la receta con el orden correcto de preprocesamiento
  rec_spec_unsw <- recipes::recipe(attack_cat ~ ., data = df_train) |>
    recipes::step_rm(label) |>  # Exclude columns
    recipes::step_novel(recipes::all_nominal_predictors(), new_level = "unknown") |>
    recipes::step_dummy(recipes::all_nominal_predictors(), one_hot = TRUE) |>
    recipes::step_zv(recipes::all_predictors()) |>
    recipes::step_normalize(recipes::all_numeric_predictors()) |>
    # Al usar all_numeric_predictors(), ya NO incluirá ni 'attack_cat' ni 'label'
    step_extract_latent(recipes::all_numeric_predictors(), epochs = 2, batch_size = 512)

  # 2. Entrenar la receta (PREP)
  # Esto dummificará, normalizará y entrenará tu modelo SCARF
  message("Entrenando pipeline completo con UNSW-NB15...")
  rec_trained_unsw <- recipes::prep(rec_spec_unsw, training = df_train)

  # 3. Procesar los datos (BAKE)
  message("Transformando el dataset UNSW-NB15...")
  unsw_transformed <- recipes::bake(rec_trained_unsw, new_data = df_train)

  # 4. Verificaciones de éxito:
  print(dim(unsw_transformed))
  # Debería tener las mismas filas que tu dataset original,
  # y exactamente 257 columnas (attack_cat + 256 de SCARF)

  # Comprobar que attack_cat sigue ahí y las variables viejas desaparecieron
  sum(c("label", "dur", "proto", "service") %in% names(unsw_transformed))
  # Debería dar 0 (las variables originales numéricas y dummificadas fueron reemplazadas)

  "attack_cat" %in% names(unsw_transformed)
  # Debería dar TRUE

  names(unsw_transformed)[!grepl("extracted_dim_", names(unsw_transformed))]
}



# Generated by Gemini. TODO: Remove in future versions
probatorio_scarf <- function() {
  # 1. Dataset de juguete: 4 filas, 4 columnas
  # Col 1: Numérica
  # Cols 2, 3, 4: One-hot de una categórica con 3 clases
  x_mat <- matrix(c(
    10.0,  1, 0, 0,  # Fila 1: Nivel A
    20.0,  0, 1, 0,  # Fila 2: Nivel B
    30.0,  0, 0, 1,  # Fila 3: Nivel C
    40.0,  1, 0, 0   # Fila 4: Nivel A
  ), nrow = 4, byrow = TRUE)

  x_tensor <- torch::torch_tensor(x_mat, dtype = torch::torch_float())

  # Definimos los grupos de variables originales
  feature_groups <- list(
    variable_num = c(1),
    variable_cat = c(2, 3, 4)
  )

  # 2. Inicializamos el callback con corrupción del 100% para forzar el intercambio
  cb <- custom_scarf_step_callback(feature_groups = feature_groups, corruption_rate = 1.0)

  # Ejecutamos la corrupción
  res <- cb$corrupt_batch(x_tensor)
  x_orig <- as.matrix(res[[1]])
  x_corr <- as.matrix(res[[2]])

  cat("==========================================")
  cat("\nMATRIZ ORIGINAL:\n")
  print(x_orig)

  cat("\nMATRIZ CORROMPIDA (corruption_rate = 1.0):\n")
  print(x_corr)
  cat("==========================================\n\n")

  # ----------------------------------------------------
  # CHECK 1: Integridad del One-Hot Encoding
  # La suma de las columnas 2, 3 y 4 DEBE ser 1 en cada fila
  # ----------------------------------------------------
  ohe_sums <- rowSums(x_corr[, 2:4])
  check_ohe <- all(ohe_sums == 1)

  if (check_ohe) {
    message("CHECK 1 PASADO: Las columnas One-Hot mantienen vectores válidos (suma = 1).")
  } else {
    stop("CECK 1 FALLADO: Hay filas con One-Hot inválido.")
  }

  # ----------------------------------------------------
  # CHECK 2: Indivisibilidad del Bloque Categórico
  # Comprobar si las columnas (2, 3, 4) se han movido JUNTAS
  # ----------------------------------------------------
  block_validity <- apply(x_corr[, 2:4], 1, function(row) {
    # Debe ser exacto a alguna de las filas originales en el bloque OHE
    any(apply(x_orig[, 2:4], 1, function(orig_row) all(row == orig_row)))
  })

  if (all(block_validity)) {
    message("CHECK 2 PASADO: El bloque One-Hot fue reemplazado como una unidad entera.")
  } else {
    stop("CHECK 2 FALLADO: Se corrompieron columnas One-Hot de forma aislada.")
  }
}


